name: Makefile CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install -y build-essential cmake ninja-build libsfml-dev libboost-container-dev

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Generate Ninja for mfGUI
      run: cd Yuna/mfGUI && cmake -G Ninja && cd ../..

    - name: compilation
      run: make
